//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffe_smrn.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OrderProduct
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public System.DateTime TimeOfOrder { get; set; }
        public string orderProducts { get; set; }
        public Nullable<decimal> sumOfOrder { get; set; }
    }
}
